name: Tests
on: push
jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
        - uses: actions/checkout@v3
        - run: make install
        - run: make test
        - run: make lint 
        - name: Code Climate Test Coverage
          uses: paambaati/codeclimate-action@v3.0.0
          env:
            CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          with:
            coverageCommand: make test-coverage
            coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
            debug: true